config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'blogs#index'
  resources :blogs
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user

  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :articles
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :move_to_index, except: [:index, :show]

  def index
    @articles = Article.includes(:user).page(params[:page]).per(6).order("created_at DESC")
  end

  def new
    @article = Article.new
  end

  def create
    Article.create(title: article_params[:title], image: article_params[:image], text: article_params[:text], user_id: current_user.id)
  end

  def destroy
    article = Article.find(params[:id])
    article.destroy if article.user_id == current_user.id
  end

  def update
    article = Article.find(params[:id])
    if article.user_id == current_user.id
      article.update(article_params)
    end
  end

  def edit
    @article = Article.find(params[:id])
  end

  def show
    @article = Article.find(params[:id])
  end

  private
  def article_params
    params.require(:article).permit(:title, :image, :text)
  end

  def move_to_index
    redirect_to action: :index unless user_signed_in?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/views/blogs/_article.html.haml
.card
  .card-image.waves-effect.waves-block.waves-light
    = image_tag article.image.url,class: "activator{"
    %span.card-title.activator
      = article.title
  .card-content
    = link_to 'SHOW', blog_path(article.id), method: :get, class: 'waves-effect waves-light btn-small cyan accent-4'
    - if user_signed_in? && current_user.id == article.user_id
      = link_to 'EDIT', edit_blog_path(article.id), method: :get, class: 'waves-effect waves-light btn-small cyan accent-4'
      = link_to 'DESTROY', "/blogs/#{article.id}", method: :delete, data: { confirm: '削除しますか？' }, class: 'waves-effect waves-light btn-small cyan accent-4'

app/views/blogs/create.html.haml
.content
  .container
    %h3
      投稿が完了しました
    .actions.waves-effect.waves-light.btn.cyan.lighten-2.action-2
      = link_to '投稿一覧へ戻る', root_path, class: 'to_index submit-btn'

app/views/blogs/destroy.html.haml
.content
  .container
    %h3
      削除が完了しました
    .actions.waves-effect.waves-light.btn.cyan.lighten-2.action-2
      = link_to '投稿一覧へ戻る', root_path, class: 'to_index submit-btn'

app/views/blogs/edit.html.haml
.content
  .container
    = form_for @article, url: {:action => 'update'} do |f|
      %h3
        編集する
      .field.cp_iptxt.cp_1
        = f.text_field :title, value: @article.title, placeholder: "", class: 'ef'
        = f.label :title
        %span.focus_line
          %i
      .field.cp_iptxt.cp_1
        = f.label :image_url, class: 'image-label' do
          = "Image Url"
        %label{for: "file_upload"}
          ファイルを選択
          = f.file_field :image, id: 'file'
          %input{type: "text", value: "ファイル選択", id: 'file_upload'}/
        %input{readonly: "readonly", size: "35", type: "text", value: @article.image.url, id: 'fake_text_box'}/
      .field.cp_iptxt.cp_1
        = f.text_area :text, value: @article.text, placeholder: "", class: 'ef'
        = f.label :text
        %span.focus_line
          %i
      .actions.waves-effect.waves-light.btn.cyan.lighten-2
        = f.submit 'SEND', class: 'submit-btn'

app/views/blogs/index.html.haml
.content
  .container
    - @articles.each do |article|
      = render partial: "article", locals: {article:article}
  = paginate(@articles)

app/views/blogs/new.html.haml
.content
  .container
    = form_for @article, url: {:action => 'create'} do |f|
      %h3
        投稿する
      .field.cp_iptxt.cp_1
        = f.text_field :title, placeholder: "", class: 'ef'
        = f.label :title
        %span.focus_line
          %i
      .field.cp_iptxt
        = f.label :image_url, class: 'image-label' do
          = f.file_field :image, class: 'image-label__input'
      .field.cp_iptxt
        = f.text_area :text, placeholder: "", class: 'ef'
        = f.label :text
        %span.focus_line
          %i
      .actions.waves-effect.waves-light.btn.cyan.lighten-2
        = f.submit 'SEND', class: 'submit-btn'

app/views/blogs/show.html.haml
.content
  .container
    .show-page-wrrap
      .card.show-page
        .card-image.waves-effect.waves-block.waves-light
          = image_tag @article.image.url,class: "activator{"
          %span.card-title.activator
            = @article.title
        .card-content
          - if user_signed_in? && current_user.id == @article.user_id
            = link_to 'EDIT', edit_blog_path(@article.id), method: :get, class: 'waves-effect waves-light btn-small cyan accent-4'
            = link_to 'DESTROY', "/blogs/#{@article.id}", method: :delete, data: { confirm: '削除しますか？' }, class: 'waves-effect waves-light btn-small cyan accent-4'
        .card-text
          %p
            = simple_format(@article.text)
            

app/views/blogs/update.html.haml
.content
  .container
    %h3
      更新が完了しました
    .actions.waves-effect.waves-light.btn.cyan.lighten-2.action-2
      = link_to '投稿一覧へ戻る', root_path, class: 'to_index submit-btn'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv": "Content-Type"}/
    %title Blog
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    / Compiled and minified CSS
    %link{href: "https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css", rel: "stylesheet"}/
    / Compiled and minified JavaScript
    %script{src: "https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"}
    / Compiled and minified icon
    %link{href: "https://fonts.googleapis.com/icon?family=Material+Icons", rel: "stylesheet"}/
    / jQuery導入
    %script{crossorigin: "anonymous", integrity: "sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU=", src: "https://code.jquery.com/jquery-3.4.1.js"}
  %body
    %nav.cyan.lighten-2
      .nav-wrapper
        %a.brand-logo{href: root_path,style: "margin-left:50px;"}
          %i.fa.fa-pencil
          BLOG
        - if user_signed_in?
          %ul#nav-mobile.right.hide-on-med-and-down{style: "margin-right:50px;"}
            %li
              = link_to "ログアウト", destroy_user_session_path, method: :delete
            %li
              = link_to "投稿", new_blog_path
        - else
          %ul#nav-mobile.right.hide-on-med-and-down{style: "margin-right:50px;"}
            %li
              = link_to "ログイン", new_user_session_path
            %li
              = link_to "新規登録", new_user_registration_path
    = yield